#!/bin/bash
# original oshcc call
if ! command -v oshcc &> /dev/null; then
    echo "couldn't find oshcc!!!!!!"
    exit 1
fi
export ORIGINAL=$(oshcc -showme)

# place our include path first
# replace first whitespace with -I./include
export REPLACE=$(echo "$ORIGINAL" | sed "s| | -I$(cd "$(dirname "$0")" && pwd)/include |")

# pass through -showme behavior
if [[ "$@" == *"-showme"* ]]; then
    echo "$REPLACE"
    exit 0
fi

$REPLACE "$@"
